//! 014 T2 golden gate: crates/gguf`s dequantize_q8_0 vs the llama.cpp
//! referee reference (tests/golden/q8_0_*.json, generated by
//! scripts/golden/gen_q8_0_golden.sh — f280b2698 dequantize_row_q8_0).
//!
//! Bit-exact (0 ulp) per 014 r2: `y = f32(q) * f32(f16(scale))` single
//! multiply semantics. The golden embeds the input block bytes so tests
//! stay hermetic (no live archive needed); regenerate to add new blocks.

use reinfer_gguf::{codes::dequantize_q8_0, schema::GgufError};
use std::path::Path;

fn goldens() -> Vec<String> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden");
    let mut v = Vec::new();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for e in rd.flatten() {
            let n = e.file_name().to_string_lossy().into_owned();
            if n.starts_with("q8_0_") && n.ends_with(".json") {
                v.push(n);
            }
        }
    }
    v.sort();
    v
}

#[test]
fn dequant_matches_referee_goldens_bit_exact() {
    let files = goldens();
    if files.is_empty() {
        eprintln!("skipped: no golden file (run scripts/golden/gen_q8_0_golden.sh)");
        return;
    }
    for f in files {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden").join(&f);
        let doc: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let blocks = doc["blocks"].as_array().unwrap();
        assert_eq!(blocks.len(), doc["blocks"].as_array().unwrap().len());
        for b in blocks {
            let hex = b["hex"].as_str().unwrap();
            let blob: Vec<u8> = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
                .collect();
            let expect: Vec<u32> = b["f32_hex"]
                .as_array()
                .unwrap()
                .iter()
                .map(|h| u32::from_str_radix(h.as_str().unwrap(), 16).unwrap())
                .collect();
            let mut out = [0.0f32; 32];
            dequantize_q8_0(&blob, &mut out).unwrap();
            for (i, got) in out.iter().enumerate() {
                assert_eq!(
                    got.to_bits(),
                    expect[i],
                    "{f} block mismatch at elem {i}: got {:08x} expected {:08x}",
                    got.to_bits(),
                    expect[i]
                );
            }
        }
    }
}

/// 014 T2 sequence-level hook: for the live archive (env-injected), the
/// raw tensor bytes feeding dequantize_tensor must be identical to the
/// golden's embedded input (guards against reader slicing drift when the
/// block codec is already proven bit-exact by the golden).
#[test]
fn archive_tensor_matches_golden_input() {
    let Some(path) = std::env::var_os("REINFER_MODEL_GGUF") else {
        eprintln!("skipped: REINFER_MODEL_GGUF unset");
        return;
    };
    let files = goldens();
    let f = files.first().expect("golden present when archive check runs");
    let doc = serde_json::from_str::<serde_json::Value>(
        &std::fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden").join(f),
        )
        .unwrap(),
    )
    .unwrap();
    let want_sha = doc["input_sha256"].as_str().unwrap();
    let reader = reinfer_gguf::GgufReader::open(&path).unwrap();
    let t = reader.tensor("token_embd.weight").unwrap();
    let data = reader.tensor_data(t).unwrap();
    let nblocks = doc["blocks"].as_array().unwrap().len();
    let nbytes = nblocks * 34; // golden input = N raw Q8_0 blocks
    use sha2::Digest;
    let got_sha = format!("{:x}", sha2::Sha256::digest(&data[..nbytes]));
    assert_eq!(got_sha, want_sha, "tensor bytes vs golden input drift");
    // First block decode equals golden values (sequence-head check).
    let mut out = [0.0f32; 32];
    dequantize_q8_0(&data[..34], &mut out).unwrap();
    let first: Vec<u32> = doc["blocks"][0]["f32_hex"]
        .as_array()
        .unwrap()
        .iter()
        .map(|h| u32::from_str_radix(h.as_str().unwrap(), 16).unwrap())
        .collect();
    for (i, got) in out.iter().enumerate() {
        assert_eq!(got.to_bits(), first[i]);
    }
}

#[test]
fn dequant_rejects_short_blob() {
    let mut out = [0.0f32; 32];
    let err = dequantize_q8_0(&[0u8; 10], &mut out).unwrap_err();
    assert!(matches!(err, GgufError::BadData { .. }), "{err:?}");
}
